apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: gianmarco-castillo-03-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: gianmarcocastillof/gianmarco-webflux-nosql-fe:1.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: gianmarco-castillo-03-secret