apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gianmarco-castillo-03-namespace
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30002