apiVersion: v1
kind: Secret
metadata:
  name: gianmarco-castillo-03-secret
  namespace: gianmarco-castillo-03-namespace
type: Opaque
data:
  DB_NAME: dmludW0tYXctZGI=
  IS_PRODUCTION: dHJ1ZQ==
  API_URL_IP: aHR0cDovLzU0LjE5OC4xNDIuMTk5OjgwODgvdjEvYXBp